<a href="https://colab.research.google.com/github/MunjaSangeetha/Generative-AI/blob/main/Assignment_8_2_GenAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

M.Sangeetha
2303A52088
Generative AI
Assignment - 8.2

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import joblib

# Load dataset
dataset_path = "/content/winequality-red (1).csv"  # Change if needed
df = pd.read_csv(dataset_path)

# Separate features and target
X = df.drop(columns=["quality"])
y = df["quality"]

# Convert target to categorical if necessary (for classification)
y = pd.cut(y, bins=[0, 5, 6, 10], labels=[0, 1, 2])  # Adjust based on dataset
y = keras.utils.to_categorical(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Save scaler
joblib.dump(scaler, "scaler.pkl")

# Build ANN model
model = Sequential([
    Dense(12, activation='tanh', input_shape=(X_train.shape[1],)),
    Dense(24, activation='tanh'),
    Dense(30, activation='tanh'),
    Dense(20, activation='tanh'),
    Dense(10, activation='tanh'),
    Dense(y.shape[1], activation='softmax')  # Output layer for classification
])

# Compile model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train model
history = model.fit(X_train, y_train, epochs=200, batch_size=32, validation_data=(X_test, y_test))

# Save model
model.save("wine_quality_model.h5")

# Evaluate model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Calculate metrics
acc = accuracy_score(y_true, y_pred_classes)
cm = confusion_matrix(y_true, y_pred_classes)
report = classification_report(y_true, y_pred_classes)

print(f"Accuracy: {acc}")
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", report)

# Deploy model: Load and predict
def load_model_and_predict(sample_input):
    loaded_model = keras.models.load_model("wine_quality_model.h5")
    loaded_scaler = joblib.load("scaler.pkl")
    sample_input = loaded_scaler.transform([sample_input])
    prediction = loaded_model.predict(sample_input)
    return np.argmax(prediction)

# Example usage
sample_input = X_test[0]
predicted_class = load_model_and_predict(sample_input)
print("Predicted Wine Quality Category:", predicted_class)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.4032 - loss: 1.0378 - val_accuracy: 0.5750 - val_loss: 0.8645
Epoch 2/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6120 - loss: 0.8337 - val_accuracy: 0.6000 - val_loss: 0.8026
Epoch 3/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6450 - loss: 0.8025 - val_accuracy: 0.5750 - val_loss: 0.7841
Epoch 4/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6475 - loss: 0.7699 - val_accuracy: 0.6062 - val_loss: 0.7721
Epoch 5/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6456 - loss: 0.7660 - val_accuracy: 0.6000 - val_loss: 0.7703
Epoch 6/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6678 - loss: 0.7428 - val_accuracy: 0.6062 - val_loss: 0.7663
Epoch 7/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6311 - loss: 0.7869 - val_accuracy: 0.6031 - val_loss: 0.7647
Epoch 8/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6537 - loss: 0.7372 - val_accuracy: 0.5969 - 

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


Accuracy: 0.671875
Confusion Matrix:
 [[103  38   0]
 [ 40  85   7]
 [  1  19  27]]
Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.73      0.72       141
           1       0.60      0.64      0.62       132
           2       0.79      0.57      0.67        47

    accuracy                           0.67       320
   macro avg       0.70      0.65      0.67       320
weighted avg       0.68      0.67      0.67       320

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Predicted Wine Quality Category: 2
